# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git checkout $(Build.SourceBranchName)
      git remote add heroku https://heroku:$(pat)@git.heroku.com/test_app.git
      git push heroku $(Build.SourceBranchName)