mongoDbUri: mongodb+srv://ethemduzgun:scfm2021@solutioncube.azjcz.mongodb.net/solutioncube

interval: 1440

firms: 
- name: erisyem
  username: solutioncube
  password: ng254146
- name: vanucci
  username: solutioncube
  password: ng254146