#mongoDbUri: mongodb+srv://ethemduzgun:scfm2021@solutioncube.azjcz.mongodb.net/solutioncube

mongoDbUri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false

interval: 1440

firms: 
- name: erisyem
  username: solutioncube
  password: ng254146
- name: vanucci
  username: mikronsmikronize
  password: xt355238