# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with Maven & Release on Heroku On Push & Pull Request [ master ]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml      
    - name: Fetch
      run: git fetch --unshallow origin
    - name: Merge
      run: git merge HEAD:master 
    - name: Add remote
      run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Push heroku
      run: git push --force heroku HEAD:master
